# Generated by Django 5.0.6 on 2024-05-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='emal',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
