# Generated by Django 5.0.6 on 2024-06-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_estudiante_emal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'camada')},
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together={('nombre', 'apellido')},
        ),
        migrations.AlterUniqueTogether(
            name='profesor',
            unique_together={('nombre', 'apellido')},
        ),
    ]
